{% set name = "ruptures" %}
{% set version = "1.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fbcecb570af28edc0a3d754c9278a7564bc3d8c1415fd7f5571a9378399b2b2a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - cython
    - numpy
    - setuptools_scm[toml] >=3.4
  run:
    - numpy
    - python
    - scipy

test:
  imports:
    - ruptures
    - ruptures.costs
    - ruptures.datasets
    - ruptures.detection
    - ruptures.metrics
    - ruptures.show
    - ruptures.utils

about:
  home: https://github.com/deepcharles/ruptures
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Change point detection for signals, in Python
  doc_url: http://ctruong.perso.math.cnrs.fr/ruptures-docs/build/html/index.html

extra:
  recipe-maintainers:
    - rpanai
    - deepcharles
    - oboulant
