{% set name = "ruptures" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 152f5c1a2d43522233160ddceb3a4225587c159b13067dfe6bba087d71070a75

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.4

  run:
    - numpy
    - python >=3.4
    - scipy

test:
  imports:
    - ruptures
    - ruptures.costs
    - ruptures.datasets
    - ruptures.detection
    - ruptures.metrics
    - ruptures.show
    - ruptures.utils

about:
  home: https://github.com/deepcharles/ruptures
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Change point detection for signals, in Python
  doc_url: http://ctruong.perso.math.cnrs.fr/ruptures-docs/build/html/index.html

extra:
  recipe-maintainers:
    - rpanai
